name: wordfriend_app
description: WordFriend Flutter client
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  path_provider: ^2.1.3
  http: ^1.2.0
  provider: ^6.1.2
  google_sign_in: ^6.3.0
  google_fonts: ^6.2.1
  sketchy_design_lang: ^0.4.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/monster.png
    - assets/soundtracks/cotton-toys-soundroll-main-version-16753-01-17.mp3
    - assets/soundtracks/pixeltown-color-parade-main-version-41716-01-53.mp3
    - assets/soundtracks/tumbling-danijel-zambo-main-version-42313-01-05.mp3
    - assets/character/monster_arm_left_down.png
    - assets/character/monster_arm_left_wave.png
    - assets/character/monster_arm_right_down.png
    - assets/character/monster_arm_right_wave.png
    - assets/character/monster_leg_left.png
    - assets/character/monster_leg_right.png
    - assets/character/monster_body.png
    - assets/character/monster_eyes_cheering.png
    - assets/character/monster_eyes_closed.png
    - assets/character/monster_eyes_crying.png
    - assets/character/monster_eyes_funny.png
    - assets/character/monster_eyes_half_open.png
    - assets/character/monster_eyes_happy.png
    - assets/character/monster_eyes_open.png
    - assets/character/monster_mouth_big_smile.png
    - assets/character/monster_mouth_neutral.png
    - assets/character/monster_mouth_open.png
    - assets/character/monster_mouth_smile.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  web:
    generate: true
    image_path: assets/app_icon.png
